const socketEvents = {
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",

  RIDER_JOINED: "RIDER_JOINED",
  RIDER_LEFT: "RIDER_LEFT",

  DRIVER_JOINED: "DRIVER_JOINED",
  DRIVER_LEFT: "DRIVER_LEFT",

  USER_MESSAGE: "USER_MESSAGE",
  USER_TYPING: "USER_TYPING",
  USER_NOT_TYPING: "USER_NOT_TYPING",

  USER_RIDE_REQUESTED: "USER_RIDE_REQUESTED",
  USER_Ride_STARTED: "USER_TYPING_STARTED",
  USER_Ride_ENDED: "USER_RIDE_ENDED",
  USER_Ride_STATUS: "USER_RIDE_ONGOING",
  USER_Ride_REQUEST_CANCELLED: "USER_RIDE_REQUEST_CANCELLED",
  USER_Ride_REQUEST_ACCEPTED: "USER_RIDE_REQUEST_ACCEPTED",
  USER_Ride_REQUEST_REJECTED: "USER_RIDE_REQUEST_REJECTED",

  DRIVER_RIDE_REQUESTED: "DRIVER_RIDE_REQUESTED",
  DRIVER_Ride_STARTED: "DRIVER_RIDE_STARTED",
  DRIVER_Ride_ENDED: "DRIVER_RIDE_ENDED",
  DRIVER_Ride_CANCELLED: "DRIVER_RIDE_CANCELLED",
  DRIVER_Ride_REQUEST_CANCELLED: "DRIVER_RIDE_REQUEST_CANCELLED",
  DRIVER_Ride_REQUEST_ACCEPTED: "DRIVER_RIDE_REQUEST_ACCEPTED",
  DRIVER_Ride_REQUEST_REJECTED: "DRIVER_RIDE_REQUEST_REJECTED",
};

const dbCollection = {
  driver: "driver",
  rider: "rider",
  driverAssociates: "driverAssociates",
  riderAssociates: "riderAssociates",
  chat: "chat",
};

export { socketEvents, dbCollection };
